lane :test do |options|
  drive_keyfile = options[:drive_keyfile] || UI.input('Please enter Google Drive keyfile: ')
  service_account = options[:service_account] || UI.confirm('Is service account?: ')
  folder_id = options[:folder_id] || UI.input('Please enter Google Drive target id: ')
  file_to_upload = options[:upload_file] || UI.input('Please enter path for file to upload: ')

  upload_to_google_drive(
    drive_keyfile: drive_keyfile,
    service_account: service_account,
    folder_id: folder_id,
    upload_files: [file_to_upload]
  )
end
